### ISSUE TITLE
Define expected html structure (a.k.a. API)

### ISSUE THREAD

**Issue by mro** [mro/ShaarliOS#1]
currently that's rather simple, because there's so few templates actually fiddling with markup, so a ~40 LOC xslt mostly covers all what's used: [response.xslt](https://github.com/mro/ShaarliOS/blob/master/ios/ShaarliOSTests/response.xslt) (see [xslt.sh](https://github.com/mro/ShaarliOS/blob/master/ios/ShaarliOSTests/xslt.sh) how to apply it).

The [Objective-C parsing code](https://github.com/mro/ShaarliOS/blob/8ec1568edceadae0d6b0a31e834ba2bba4074ffb/ios/ShaarliOS/ShaarliM.m#L168) (~150 LOC) sadly is way less obvious.

Maybe it's a good idea to define the expected html?

**Comment by mro** [comment]
https://github.com/shaarli/Shaarli/issues/16

**Comment by mro** [comment]
a scary compatibility chart: https://travis-ci.org/mro/phptestdemo/builds/78854177

**Comment by mro** [comment]
continued from https://github.com/mro/ShaarliOS/issues/2#issuecomment-138078054:

ic, so you may be interested in what I'm doing at test-post.sh - that's the flow I use to add/post a link.

There's a strange issue I could need help with - I don't understand why the Atom Feed brings strange results after adding a link for some php/shaarli version combinations.

I'd very much appreciate if you could you have a look

if the flow in test-post.sh is what your app uses,
you can help me understand why adding the link doesn't fully work (at least in terms of the atom feed)
P.S.: a full list of all php/shaarli versions covered by travis: https://travis-ci.org/mro/Shaarli-API-test/builds/78946245

**Comment by mro** [comment]
so finally the complicated/underspecified things IMO are

- logged-in state (which may imply from other `<input` fields, dependent on the context)
- find shaarli title (optional, robust from Atom feed)
- error messages.

@dimtion what else do you think?

**Comment by mro** [comment]
Ouch. How to detect a successful add? See https://github.com/shaarli/Shaarli/issues/308#issuecomment-141366230

**Comment by mro** [comment]
try to get PR https://github.com/shaarli/Shaarli/pull/354 through.

**Comment by mro** [comment]
plus try to get PR shaarli/Shaarli#357 through.

**Comment by mro** [comment]
seems done, `scripts/test-post.sh` and `scripts/test-login.sh` of https://github.com/mro/Shaarli-API-test seem to be what's needed minimally. 

@dimtion what do you think, does that make sense and help future development, both of clients as yours and mine and shaarli itself?

**Comment by dimtion** [comment]
If I understand well this is a tool to check if a Shaarli is compatible with the current "API" ?

So yes it could be good thing to add to Shaarli's testing tool chain, because if any regression made through to production It could become painful for us to keep track of multiple interfaces. So for the moment, it is a good turnaro

**Comment by dimtion** [comment]
If I understand well this is a tool to check if a Shaarli is compatible with the current "API" ?

So yes it could be good thing to add to Shaarli's testing tool chain, because if any regression made through to production It could become painful for us to keep track of multiple interfaces. So for the moment, it is a good thing to keep. You should propose it to Shaarli maintainers to avoid us missing a release.

About the code it self, I need more time to review it, but it seems enough for what we need now.
