### ISSUE TITLE
Use shaarli response field presets

### ISSUE THREAD

**Issue by mro** [mro/ShaarliOS#4]
currently when posting a link we start network interaction *after* tapping `Post`.

Thus e.g. the server-side url cleanup and other (server-side) field defaults are overwritten.

Todo: start server interaction early and present the response as defaults. Additional benefit: ShaarliOS can modify existing links.

**Comment by mro** [comment]
There is a UX issue here - the server roundtrip takes time prior editing. @dimtion How do you handle this?

**Comment by dimtion** [comment]
Yes server defaults are overwritten like fetching description field or fetching title field.

But I don't think this is really a problem since the user doesn't really want exactly the same behavior on his phone and on the web interface.

The solution I use for the moment, is to launch the interface with prefetched data that the app sent me (like the title of the link and the url) ; show a loading icon on empty fields (like the description field) while download the missing data. If the user start editing a field I stop the network request and keep the entered data.

**Comment by mro** [comment]
it's the timing. When sharing the dialog should wait until the server response comes in. How would the server response and simultaneous user input be merged?

But blocking until the server responds (>0.5 sec usually) when the large amount of use cases is *NOT* editing *existing* entries sounds bad to me, too.

What do you think? Forbid edit or wait for response?

**Comment by dimtion** [comment]
What I do is to notify the user that the application is waiting for a response from the server, but I don't block the user to enter his own value. If he does so I discard the server response.
Also, if the user press "post" before the first response arrive I wait for the response before posting.

I think this system is quite reliable because if the user want to write down his own description he won't be bothered by the server response delay.

**Comment by mro** [comment]
indeed, sounds like the way to go.

**Comment by dimtion** [comment]
IMHO, blindly wait for the server response while blocking user input can become very frustrating.

I hope I could helped you.

**Comment by mro** [comment]
yes, thank you, you did very much so. I thought about blocking and an aggressive timeout (<5sec) but your approach is by far superior.

**Comment by mro** [comment]
added in v1.1 9b428a6
